include ../Makefile.plugin.common

ifdef IS_WINDOWS
    LDFLAGS += 
    # Folosește += pentru a ADAUGA fișierele, nu pentru a le înlocui pe cele locale
    SRCS += ../../StringUtils.cpp ../../ConsoleManager.cpp ../../OliEngine.cpp ../../OliCompiler.cpp ../../PortTools.cpp ../../ASTNode.cpp ../../OliFuncHandlers.cpp ../../OliExecuteBytecode.cpp
else
    LDFLAGS += 
endif