# src/plugins/oli_sprites/Makefile
SRCS = ../../StringUtils.cpp ../../ConsoleManager.cpp ../../OliEngine.cpp ../../OliCompiler.cpp ../../PortTools.cpp ../../ASTNode.cpp ../../OliFuncHandlers.cpp ../../OliExecuteBytecode.cpp
include ../Makefile.plugin.common